### PR TITLE
Fix some process leaks.

### LINKED ISSUE #129: Steam leaks fossilize_replay children in stopped state
When Steam crashes (and maybe also when quit normally) while fossilze_replay is running, it may leak fossilize_replay processes in stopped state (as part of the load limiter which `SIG_STOP`s children). The main process should probably send `SIG_CONT` to all children before exiting or being forcefully quit.

### PR DESCRIPTION
**Pull request by HansKristian-Work**
- Need to use SIGKILL to ensure that stopped child processes actually
  die. The replayer handled this correctly, but not the external
  replayer API.
- Need to use SEQPACKET socket type to actually be able to detect
  hangups. socketpair() DGRAMs apparently don't work even if they are
  connected ...

Fix #129.

### CODE REVIEW

File: fossilize_external_replayer_linux.hpp [hunk 1]
```diff
@@ -418,7 +418,7 @@ bool ExternalReplayer::Impl::kill()
 		kill_fd = -1;
 	}
 
-	bool ret = killpg(pid, SIGTERM) == 0;
+	bool ret = killpg(pid, SIGKILL) == 0;
```
Comment (kakra) [inline fossilize_external_replayer_linux.hpp:421]: I'm not sure if this is enough because the leaking processes in stopped state didn't go away when I sent SIGKILL manually, it needed an additional SIGCONT. But let's see how it changes once this update is deployed.

Comment (HansKristian-Work) [reply fossilize_external_replayer_linux.hpp:421]: I tested this and SIGKILLing a stopped child worked just fine.
